In [1]:
"""
Name : Govind Sahai
Roll : 13123006
Year : Fourth
"""
"""
Q2. Write the code for the Power method to find the most dominant eigenvalue of the given matrix
"""

'\nQ2. Write the code for the Power method to find the most dominant eigenvalue of the given matrix\n'

In [2]:
import numpy as np
import math

In [3]:
mat = np.array([[   5.,  -2., -0.5,  1.5],
                [  -2.,   5.,  1.5, -0.5],
                [ -0.5,  1.5,   5.,  -2.],
                [  1.5, -0.5,  -2.,   5.]])

In [4]:
tolerance = 10 ** -4
def getNextX(A, x, last_eig):
    mul = np.dot(A, x)
    eig = abs(mul).max()
    mul = mul / eig
    if last_eig is None: return (False, eig, mul)
    elif abs(eig - last_eig) < tolerance: return (True, eig, mul)
    else: return (False, eig, mul)

In [5]:
dim = mat.shape[0]
x = mat[0]

(found, last_eig, x) = getNextX(mat, x, None)
i = 0
while not found:
    i += 1
    (found, last_eig, x) = getNextX(mat, x, last_eig)

print "Largest Eigen Value[Magnitude] : ", last_eig
print "Total number of iterations : ", i

Largest Eigen Value[Magnitude] :  8.99989605235
Total number of iterations :  17


In [6]:
"""
Q3. Use Householder’s method to find the tridiagonal form of the following matrix. 
Also write the code to find the tridiagonal form by using Householder's method of the given matrix.
"""

"\nQ3. Use Householder\xe2\x80\x99s method to find the tridiagonal form of the following matrix. \nAlso write the code to find the tridiagonal form by using Householder's method of the given matrix.\n"

In [7]:
def GetTrigonalizedMatrix(mat):
    from libhouseholder import GetTrigonalizedMatrix_
    matAsList = mat.tolist()
    trigonalizedMatrix = GetTrigonalizedMatrix_(matAsList)
    res = np.array(trigonalizedMatrix)
    return res

In [8]:
print GetTrigonalizedMatrix(mat)

[[  5.00000000e+00   2.54950976e+00  -1.10894266e-16   4.38008032e-16]
 [  2.54950976e+00   6.38461538e+00   2.14075693e+00  -6.66133815e-16]
 [ -1.10894266e-16   2.14075693e+00   4.27000050e+00  -6.91280890e-01]
 [  4.38008032e-16   0.00000000e+00  -6.91280890e-01   4.34538412e+00]]


In [9]:
"""
Q4. Write the code for QR algorithm to determine, to within10 −5 , all the eigenvalues of the following matrix.
"""

'\nQ4. Write the code for QR algorithm to determine, to within10 \xe2\x88\x925 , all the eigenvalues of the following matrix.\n'

In [10]:
A = np.array([[  2., -1.,  0.],
              [ -1., -1., -2.],
              [  0., -2.,  3.]])

In [11]:
tolerance = 10 ** -5
def getNextA(last_A, i):
    print '\tIteration -- ', i
    b, c = np.linalg.qr(last_A)
    new_A = c * b
    error = np.diag(new_A) - np.diag(last_A)
    print 'np.diag(new_A) \t: ', np.diag(new_A)
    print 'np.diag(last_A) : ', np.diag(last_A)
    print 'error \t\t: ', error
    mean_error = np.sqrt(np.sum(np.square(error)))
    print 'mean_error \t: ', mean_error
    if mean_error < tolerance:
        return (True, new_A)
    else:
        return (False, new_A)

In [12]:
i = 1
(found, A) = getNextA(A, i)
while not found:
    i += 1
    (found, A) = getNextA(A, i)
print 'Total Number of iterations : ', i
print 'Eigen Values : ', np.diag(A)

	Iteration --  1
np.diag(new_A) 	:  [ 2.         -1.2         1.75862069]
np.diag(last_A) :  [ 2. -1.  3.]
error 		:  [ -2.22044605e-16  -2.00000000e-01  -1.24137931e+00]
mean_error 	:  1.25738720852
	Iteration --  2
np.diag(new_A) 	:  [ 2.         -1.2         1.75862069]
np.diag(last_A) :  [ 2.         -1.2         1.75862069]
error 		:  [ 0.  0.  0.]
mean_error 	:  0.0
Total Number of iterations :  2
Eigen Values :  [ 2.         -1.2         1.75862069]
